[PR] Adicionado ngModel e ngChange
gigioSouza/ng-currency-range-slider pull request #2
Opened 2018-04-27 20:49 UTC by walkerdepaula

2018-04-28 00:51 UTC, sougiovn requested changes

2018-04-28 00:51 UTC, gigioSouza commented on src/main.js
> +    self.test = {};
Remover

2018-04-28 00:51 UTC, gigioSouza commented on src/ng-currency-range-slider.js
>          onRangeChange: '&'
Trocar por `ngChange`

2018-04-28 00:51 UTC, gigioSouza commented on src/ng-currency-range-slider.js
> +        $scope.onRangeChange({
Trocar por `ngChange`

2018-05-02 12:56 UTC, walkerdepaula commented on src/main.js
> +    self.test = {};
Fix in b266fbd

2018-05-02 12:56 UTC, walkerdepaula commented on src/ng-currency-range-slider.js
>          onRangeChange: '&'
Fix in b266fbd

2018-05-02 12:56 UTC, walkerdepaula commented on src/ng-currency-range-slider.js
> +        $scope.onRangeChange({
Fix in b266fbd

2018-05-02 15:24 UTC, sougiovn approved these changes

2018-05-02 15:24 UTC, merged